import { ArrowLeft, Check, X } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { format } from "date-fns";
import { Role } from "@prisma/client";
import { reviewTimesheet } from "@/actions/manager";
import { StatusBadge } from "@/components/ui/status-badge";
import { requireRole } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { formatDuration } from "@/lib/utils";
import { weekLabel } from "@/lib/dates";
export default async function ReviewPage({params}:{params:Promise<{id:string}>}){await requireRole([Role.MANAGER,Role.ADMIN]);const {id}=await params;const row=await prisma.timesheet.findUnique({where:{id},include:{user:true,entries:{include:{project:true},orderBy:{date:"asc"}}}});if(!row)notFound();const total=row.entries.reduce((s,e)=>s+e.minutes,0);return <><Link href="/manager" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-[#52615d]"><ArrowLeft size={17}/>Approval queue</Link><div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-3"><h1 className="text-3xl font-bold">{row.user.name}</h1><StatusBadge status={row.status}/></div><p className="mt-2 text-[#66736f]">{weekLabel(row.weekStart)} · {formatDuration(total)}</p></div></div><div className="panel overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead><tr className="border-b bg-[#f8faf9] text-xs uppercase text-[#65736f]"><th className="px-5 py-3">Date</th><th className="px-5 py-3">Project</th><th className="px-5 py-3">Description</th><th className="px-5 py-3 text-right">Hours</th></tr></thead><tbody>{row.entries.map(e=><tr key={e.id} className="border-b"><td className="px-5 py-4 text-sm font-semibold">{format(e.date,"EEE, MMM d")}</td><td className="px-5 py-4 text-sm">{e.project.code} · {e.project.name}</td><td className="px-5 py-4 text-sm text-[#52615d]">{e.description||"-"}</td><td className="px-5 py-4 text-right font-bold">{formatDuration(e.minutes)}</td></tr>)}</tbody></table></div>{row.status==="SUBMITTED"&&<form action={reviewTimesheet} className="panel mt-6 p-5"><label className="label" htmlFor="note">Review note</label><textarea id="note" name="note" rows={3} className="input" placeholder="Optional for approval; required for rejection"/><input type="hidden" name="timesheetId" value={id}/><div className="mt-4 flex justify-end gap-3"><button name="decision" value="REJECTED" className="btn btn-danger"><X size={18}/>Request changes</button><button name="decision" value="APPROVED" className="btn btn-primary"><Check size={18}/>Approve</button></div></form>}</>}
