import { Clock3, Inbox, Users } from "lucide-react";
import Link from "next/link";
import { Role } from "@prisma/client";
import { StatusBadge } from "@/components/ui/status-badge";
import { requireRole } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { formatDuration } from "@/lib/utils";
import { weekLabel } from "@/lib/dates";
export const metadata={title:"Team review"};
export default async function ManagerPage(){await requireRole([Role.MANAGER,Role.ADMIN]);const [pending,employees,approved]=await Promise.all([prisma.timesheet.findMany({where:{status:"SUBMITTED"},include:{user:true,entries:true},orderBy:{submittedAt:"asc"}}),prisma.user.count({where:{role:"EMPLOYEE",active:true}}),prisma.timesheet.count({where:{status:"APPROVED"}})]);return <><div className="mb-7"><h1 className="text-3xl font-bold">Team review</h1><p className="mt-2 text-[#66736f]">Review submitted time and keep payroll moving.</p></div><div className="mb-6 grid gap-4 sm:grid-cols-3"><SmallMetric icon={Inbox} label="Awaiting review" value={String(pending.length)}/><SmallMetric icon={Users} label="Active employees" value={String(employees)}/><SmallMetric icon={Clock3} label="Approved records" value={String(approved)}/></div><div className="panel overflow-hidden"><div className="border-b p-5"><h2 className="font-bold">Approval queue</h2><p className="mt-1 text-sm text-[#66736f]">Oldest submissions appear first.</p></div>{pending.length?pending.map(row=><Link href={`/manager/timesheets/${row.id}`} key={row.id} className="grid gap-3 border-b px-5 py-4 last:border-0 hover:bg-[#fafbfa] md:grid-cols-[1fr_1fr_.5fr_.5fr]"><div><div className="font-bold">{row.user.name}</div><div className="mt-1 text-xs text-[#66736f]">{row.user.department}</div></div><div className="text-sm font-semibold">{weekLabel(row.weekStart)}</div><div className="text-sm font-bold">{formatDuration(row.entries.reduce((s,e)=>s+e.minutes,0))}</div><StatusBadge status={row.status}/></Link>):<div className="p-12 text-center"><Inbox className="mx-auto mb-3 text-[#92a09c]"/><div className="font-bold">All caught up</div><div className="mt-1 text-sm text-[#66736f]">There are no timesheets waiting for review.</div></div>}</div></>}
function SmallMetric({icon:Icon,label,value}:{icon:typeof Inbox;label:string;value:string}){return <div className="panel flex items-center gap-4 p-5"><span className="grid size-10 place-items-center rounded-md bg-[#e8f4f1] text-[#087f6b]"><Icon size={19}/></span><div><div className="text-2xl font-bold">{value}</div><div className="text-xs font-semibold text-[#66736f]">{label}</div></div></div>}
