import { CalendarDays, Clock3, House, LayoutDashboard, Repeat2, Users } from "lucide-react";
import Link from "next/link";
import type { User } from "@prisma/client";
import { initials } from "@/lib/utils";

type EmployeeIdentity=Pick<User,"name"|"employeeCode"|"jobTitle"|"department">;
type AppShellProps={mode:"employee"|"manager";employee?:EmployeeIdentity;children:React.ReactNode};

export function AppShell({mode,employee,children}:AppShellProps) {
  const manager=mode==="manager";
  const links=manager?[{href:"/manager",label:"Team timesheets",icon:Users}]:[{href:"/dashboard",label:"Overview",icon:LayoutDashboard},{href:"/timesheets",label:"My tracking",icon:CalendarDays}];
  const home=manager?"/manager":"/dashboard";
  return <div className="min-h-screen md:grid md:grid-cols-[232px_1fr]">
    <aside className="desktop-only fixed inset-y-0 left-0 z-20 flex w-[232px] flex-col bg-[#102a26] px-3 py-5 text-white"><Link href={home} className="mb-8 flex items-center gap-3 px-3 text-xl font-bold"><span className="grid size-9 place-items-center rounded-md bg-[#22a98f]"><Clock3 size={20}/></span>Time Track</Link><nav className="space-y-1">{links.map(({href,label,icon:Icon})=><Link key={href} href={href} className="flex items-center gap-3 rounded-md px-3 py-2.5 text-sm font-semibold text-[#c8dad5] hover:bg-white/10 hover:text-white"><Icon size={18}/>{label}</Link>)}</nav><div className="mt-auto border-t border-white/10 pt-4">{manager?<><div className="mb-3 px-3"><div className="text-sm font-bold">Manager View</div><div className="mt-1 text-xs text-[#91aaa4]">Public team overview</div></div><Link href="/" className="flex items-center gap-3 rounded-md px-3 py-2 text-sm text-[#c8dad5] hover:bg-white/10"><House size={17}/>Back to home</Link></>:employee?<><div className="mb-3 flex items-center gap-3 px-2"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-[#d8efe9] text-xs font-bold text-[#075f51]">{initials(employee.name)}</span><div className="min-w-0"><div className="truncate text-sm font-bold">{employee.name}</div><div className="truncate text-xs text-[#91aaa4]">{employee.employeeCode||"Employee"}</div></div></div><Link href="/employee" className="flex items-center gap-3 rounded-md px-3 py-2 text-sm text-[#c8dad5] hover:bg-white/10"><Repeat2 size={17}/>Switch employee</Link></>:null}</div></aside>
    <div className="md:col-start-2"><header className="sticky top-0 z-10 flex min-h-16 items-center justify-between gap-3 border-b border-[#dce3e0] bg-white px-4 py-2 md:px-8"><Link href={home} className="flex items-center gap-2 font-bold md:hidden"><Clock3 className="text-[#087f6b]"/>Time Track</Link><div className="desktop-only text-sm font-semibold text-[#52615d]">{manager?"Manager View":"Employee Mode"}</div>{manager?<Link href="/" className="btn btn-secondary"><House size={17}/>Back to home</Link>:employee?<div className="ml-auto flex min-w-0 items-center gap-3"><div className="min-w-0 text-right"><div className="truncate text-sm font-bold">{employee.name}</div><div className="truncate text-xs text-[#66736f]">{employee.employeeCode||"Employee"} · {employee.jobTitle||employee.department||"Team member"}</div></div><Link href="/employee" title="Switch employee" aria-label="Switch employee" className="grid size-9 shrink-0 place-items-center rounded-md border border-[#cbd5d1] text-[#52615d] hover:bg-[#f6f8f7]"><Repeat2 size={17}/></Link></div>:null}</header><main className="mx-auto max-w-[1280px] p-4 pb-24 md:p-8">{children}</main><nav className={`fixed inset-x-0 bottom-0 z-20 grid border-t bg-white py-2 md:hidden ${manager?"grid-cols-2":"grid-cols-3"}`}>{links.map(({href,label,icon:Icon})=><Link key={href} href={href} className="flex flex-col items-center gap-1 text-[10px] text-[#52615d]"><Icon size={18}/>{label.split(" ")[0]}</Link>)}<Link href={manager?"/":"/employee"} className="flex flex-col items-center gap-1 text-[10px] text-[#52615d]">{manager?<House size={18}/>:<Repeat2 size={18}/>}Exit</Link></nav></div>
  </div>;
}
