import { ArrowLeft, Download, Trash2 } from "lucide-react";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { format } from "date-fns";
import { Role } from "@prisma/client";
import { deleteEntry } from "@/actions/timesheets";
import { EntryForm } from "@/components/entry-form";
import { requireUser } from "@/lib/auth";
import { dateKey, weekLabel } from "@/lib/dates";
import { prisma } from "@/lib/prisma";
import { formatDuration } from "@/lib/utils";

export default async function TimesheetDetail({params}:{params:Promise<{id:string}>}) { const user=await requireUser(); if(user.role===Role.MANAGER||user.role===Role.ADMIN)redirect("/manager"); const {id}=await params; const timesheet=await prisma.timesheet.findFirst({where:{id,userId:user.id},include:{entries:{orderBy:[{date:"asc"},{createdAt:"asc"}]}}}); if(!timesheet) notFound(); const total=timesheet.entries.reduce((s,e)=>s+e.minutes,0); return <><Link href="/timesheets" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-[#52615d]"><ArrowLeft size={17}/>All weeks</Link><div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">{weekLabel(timesheet.weekStart)}</h1><p className="mt-2 text-[#66736f]">{formatDuration(total)} recorded across {timesheet.entries.length} entries</p></div><a href={`/api/reports/timesheets/${id}`} className="btn btn-secondary"><Download size={18}/>Weekly PDF</a></div><div className="mb-6"><EntryForm timesheetId={id} defaultDate={dateKey(timesheet.weekStart)}/></div><div className="panel overflow-hidden"><table className="w-full border-collapse text-left"><thead><tr className="border-b bg-[#f8faf9] text-xs uppercase text-[#65736f]"><th className="px-5 py-3">Date</th><th className="px-5 py-3 text-right">Hours</th><th className="w-14"/></tr></thead><tbody>{timesheet.entries.map(entry=><tr key={entry.id} className="border-b last:border-0"><td className="whitespace-nowrap px-5 py-4 text-sm font-semibold">{format(entry.date,"EEE, MMM d")}</td><td className="px-5 py-4 text-right font-bold">{formatDuration(entry.minutes)}</td><td><form action={deleteEntry}><input type="hidden" name="entryId" value={entry.id}/><button title="Delete entry" aria-label="Delete entry" className="grid size-9 place-items-center text-[#a53b34] hover:bg-red-50"><Trash2 size={17}/></button></form></td></tr>)}{!timesheet.entries.length&&<tr><td colSpan={3} className="px-5 py-12 text-center text-[#66736f]">No time recorded for this week.</td></tr>}</tbody><tfoot><tr className="border-t-2 bg-[#fafbfa]"><td className="px-5 py-4 text-right text-sm font-bold">Weekly total</td><td className="px-5 py-4 text-right text-lg font-bold text-[#087f6b]">{formatDuration(total)}</td><td/></tr></tfoot></table></div></>; }
